apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels: 
    app: api-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
      - name: api-container
        image: davidfordj98/task2app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-deployment
spec:
  type: ClusterIP
  selector:
    app: api-deployment
  ports:
  - protocol: TCP
    port: 8080  
    targetPort: 8080